project_name: misskey-mcp-server

builds:
  - main: ./cmd/misskey-mcp-server/main.go
    binary: misskey-mcp-server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0 # Optional: common for GoReleaser to ensure static binaries

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
